spring:
  profiles:
    active: dev
---
server:
  port: 9001

spring:
 datasource:
  url: jdbc:mysql://47.104.234.234:3306/pygdb?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
  username: root
  password: root
  driver-class-name: com.mysql.jdbc.Driver
mybatis:
  configuration:
    map-underscore-to-camel-case: true