spring:
  profiles:
    active: dev
---
server:
  port: 7001

spring:
  redis:
   database: 0
   host: 127.0.0.1
   port: 6379
   jedis:
    pool:
     max-active: 8
     max-idle: 8
     min-idle: 0

#  thymeleaf:
#    suffix: .html
#    prefix: classpath:/templates/

  datasource:
    url: jdbc:mysql://47.104.234.234:3306/pygdb?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  configuration:
    map-underscore-to-camel-case: true